### ISSUE TITLE
Weather widget ignores `middle` class  in mobile mode

### ISSUE THREAD

**Issue by derkork** [th3jesta/ha-lcars#102]
I have set up a weather widget stack liket this:

```yaml
type: vertical-stack
cards:
  - type: markdown
    content: '# Planetares Wetter'
    card_mod:
      class: header
  - type: weather-forecast
    show_forecast: false
    show_current: true
    name: AKTUELL
    forecast_type: daily
    entity: weather.home
    card_mod:
      class: middle
  - type: weather-forecast
    show_forecast: true
    show_current: false
    name: AKTUELL
    forecast_type: daily
    entity: weather.home
    card_mod:
      class: middle
  - type: entity
    card_mod:
      class: middle
    entity: sensor.sun_next_dawn
  - type: entity
    entity: sensor.sun_next_dusk
    card_mod:
      class: middle
  - type: markdown
    content: '### &nbsp; '
    card_mod:
      class: footer

```

On the desktop this renders nicely to:

<img width="523" alt="image" src="https://github.com/user-attachments/assets/d8a08632-0360-4200-9606-94a73ec44508">

However in mobile mode the `middle` class seems to be ignored for the weather widget and I get this:

![Screenshot_20240725_094236_Home Assistant](https://github.com/user-attachments/assets/2e93fb05-773a-47de-bccc-ced3d83eefbf)
