### ISSUE TITLE
Lcars 3.0, problem with custom:formula-one-card

### ISSUE THREAD

**Issue by MichelJourdain** [th3jesta/ha-lcars#109]
I have a problem with this card with the new version of the theme (Lcars 3.0), I get an error and HA goes into a loop. If I put the previous version back, it works.

The card in problem:

 https://github.com/marcokreeft87/formulaone-card.

Error message in Web Inspector:

![image](https://github.com/user-attachments/assets/c4ed81cf-3f4a-4d93-8c6e-f9138d7b60ff)

![image](https://github.com/user-attachments/assets/85c61441-0b6c-49db-8540-6bb3eaefdfe9)

Code:

The card: 
```
              - type: custom:formulaone-card
                card_type: countdown
                show_raceinfo: true
                f1_font: true
                only_show_date: true
                show_refresh: true
                translations:
                  days: j
                  hours': h
                  minutes': m
                  seconds': s
                  date: Date
                  practice1: Essais libres 1
                  practice2: Essais libres 2
                  practice3: Essais libres 3
                  race: Course
                  racename: Nom
                  circuitname: Piste
                  location: Endroit
                  city: Ville
                  racetime: Course
                  sprint: Sprint
                  qualifying: Qualifications
                  endofseason: Saison terminée
                show_carnumber: true
                hide_tracklayout: false
                location_clickable: true
                hide_racedatetimes: false
                show_weather: false
                card_mod:
                  class: middle-contained
```
