### ISSUE TITLE
Why is it not the same as your examples?

### ISSUE THREAD

**Issue by rchadgray** [th3jesta/ha-lcars#122]
I entered code just like your example and the headers do not look the same.

I have tried many of the different themes includeing LCARS Default.

![image](https://github.com/user-attachments/assets/ff50b577-0a81-4f48-b7e1-5e9210c95b98)

**Comment by nerotrobe** [comment]
I'm experiencing the same issue, Initially I thought this had something to do with using header in the examples but switching it to use header-left results in the same issue. Then I thought it might be something to do with the Section view, but it does the same thing on masonry

**Comment by th3jesta** [comment]
Please see Known Issues in the README. July/August Home Assistant update broke Markdown card compatibility with card-mod. Card-mod owner has not fixed it, and probably will not fix it, so we now recommend using the HTML card available in HACS instead. More details can be found in the Known Issues.

**Comment by rchadgray** [comment]
OK i found this code worked for me.  After i installed the 

```
type: vertical-stack
cards:
  - type: custom:html-card
    title: ""
    content: |
      <h1>External Atmopshere Climate</h1>
    card_mod:
      class: header-left
  - type: weather-forecast
    entity: weather.forecast_home
    forecast_type: daily
    card_mod:
      class: middle-left
```
