### ISSUE TITLE
Background color changed!

### ISSUE THREAD

**Issue by Doni49** [th3jesta/ha-lcars#123]
My dashboard is configured to use LCars Modern.  Up until last night all the title cards had a background cooler that was a shade of yellow or orange.  Now they're black.  Any ideas how I can fix it?  I don't like the black background.

![dsshboard](https://github.com/user-attachments/assets/075a30e3-cc68-44b3-952a-abda5564e9d0)

P.S. this is the YAML code behind one of the title cards.

```
type: custom:mushroom-title-card
title: Office
```

**Comment by th3jesta** [comment]
Does your card include any references to card_mod? It should include something like
```yaml
type: custom:mushroom-title-card
title: Office
card_mod:
  class: header-left
```
I'm not sure what it looked like before, but if it just had a color background, try using `class: button-large`.
