### ISSUE TITLE
thick left bar in dashboard

### ISSUE THREAD

**Issue by atopetiff** [th3jesta/ha-lcars#126]
since lcars has thick left (or right) bars i created them in my template by adding a bit to your css.
under
```yaml
(DO NOT USE/MODIFY)=== card-mod CSS: &card-mod-css # Card modifications
  card-mod-card-yaml: &card-mod-card |
```
i added:
```css
/* =============================================== */
/*            ATOPE-TIFF-OVERWRITES                */
/* =============================================== */
ha-card.header-left.header-menu-left,
ha-card.header-right.header-menu-left,
ha-card.header-contained.header-menu-left,
ha-card.header-open.header-menu-left{
    border-left-width: calc(var(--ov-lcars-border-left) - 8px);
}
ha-card.middle-left.middle-menu-left{
    border-left-width: calc(var(--ov-lcars-border-left) - 8px);
}
ha-card.footer-left.footer-menu-left,
ha-card.footer-right.footer-menu-left,
ha-card.footer-contained.footer-menu-left,
ha-card.footer-open.footer-menu-left{
    border-left-width: calc(var(--ov-lcars-border-left) - 8px);
}
```
--ov-lcars-border-left is mostly set with 8rem;

btw i modified your mushroom as well because most color combinations are very hard to read:
```css
ha-card.type-custom-mushroom-chips-card > * {
    --primary-text-color: white;
    font-size: 4rem;
    padding: 0;
 }
```

I appreciate your work very much. Even more since i learned how hard it is to style homeassitant ([my little usage of your theme](https://github.com/atopetiff/ha-automated-lcars/blob/main/lcars.yaml)).
