### ISSUE TITLE
[Theme broken starting with 2025.01] Order of HTML elements in Homeassistant has changed

### ISSUE THREAD

**Issue by Lichtblitz** [th3jesta/ha-lcars#134]
The theme worked fine until it first broke in the browser and much later (maybe the styles were cached in the app?) on the Homeassistant app. I have now found the time to investigate further.

**Steps to reproduce**

1. use the example snippet from the README:
```
type: vertical-stack
cards:
  - type: custom:html-card
    card_mod:
      class: header-left
    content: '# Climate'
  - type: weather-forecast
    entity: weather.home
    card_mod:
      class: middle-left
  - type: thermostat
    entity: climate.dining_room
    card_mod:
      class: footer-left
```
2. Observe that the elements are not styled:
![Image](https://github.com/user-attachments/assets/012bf8e6-2b7b-4f18-8d7a-32815dd1d73a)

3. Check the HTML source code of the page:
![Image](https://github.com/user-attachments/assets/19bf4716-97fa-4263-9548-2eb0bc887223)

As you can see, the classes `header-left` and `type-custom-html-card` are on the same element and `ha-card` is underneath both.

4. Manually add `header-left` to the `ha-card` element in the source code and observe that the corresponding element is now properly styled:
![Image](https://github.com/user-attachments/assets/485f4c81-44ba-4d80-9df1-7ee4d700ba62)

**Environment**
I'm currently on 2025.2, but the issue was present at least since 2025.1. All HACS-Plugins are up to date, including card-mod

**Pull Request**
I'm ready to create a Pull Request to fix the CSS selectors for the errors I can find as long as someone can verify that this is a general issue and not something related to a misconfiguration on my end.
