### ISSUE TITLE
Cleanup font color assignments

### ISSUE THREAD

**Issue by th3jesta** [th3jesta/ha-lcars#16]
Right now:
```yaml
  primary-text-color: var(--lcars-text-gray)
  secondary-text-color: var(--lcars-text-gray)
  text-primary-color: var(--lcars-text-gray)
```
This is great for cards with black backgrounds, but assigning the text color `var(--lcars-text-gray)` destroys the legibility of text on menu pages outside of dashboards. It may be better to assign the primary text color to black, and update the dark background cards to use `var(--lcars-text-gray)`. This will be quite a bit to make sure all text in all places renders legibly, as it was quite a bit of work to get it in the hodge-podge state it's in now.
