### ISSUE TITLE
Setting LCARS as front-end theme messes up the sidebar

### ISSUE THREAD

**Issue by Xiondewah** [th3jesta/ha-lcars#22]
When I run the automation to set the them, once I refresh the browser the sidebar only shows the very top part - I can't access any of the additional buttons/links.

It does work properly until I refresh the browser and clearing my cache doesn't solve the problem.

**Comment by th3jesta** [comment]
Can you please provide a screenshot of what you are seeing? Thanks.

**Comment by Xiondewah** [comment]
[image0.jpeg]
Jonathan

On 4 Jan 2023, at 15:06, Jonathan Drake ***@***.***> wrote:

﻿
<385CDF35-1B69-416D-89E8-4D1BDB22226D.jpeg>

**Comment by th3jesta** [comment]
Sorry Jonathan, that didn't work:
<img width="706" alt="image" src="https://user-images.githubusercontent.com/38670315/210611716-8791fb58-fecc-46b4-ad64-a26e7ca17c75.png">

**Comment by Xiondewah** [comment]
![1F5E6376-865A-4D7A-A421-876C6750D301](https://user-images.githubusercontent.com/50043329/210612768-a46506d9-0b06-49ab-962f-40fa77c96249.jpeg)

you’ll also notice that there are no gaps between the sidebar button - hopefully this one works 😁

**Comment by Xiondewah** [comment]
Sorry you can’t see the buttons of course!

**Comment by th3jesta** [comment]
Yeah, that ain't right. Looks like an incompatibility.
What other front-end mods do you have installed?

**Comment by Xiondewah** [comment]
None as far as I know - this was the first one I added.

**Comment by Xiondewah** [comment]
What sort of thing might affectnit\/

**Comment by th3jesta** [comment]
Did you call the reload themes service?

**Comment by th3jesta** [comment]
> What sort of thing might affectnit/

Anything that modifies the sidebar or header bar could potentially break things. Another user bulk-disabled a bunch of custom cards he wasn't using anymore, and that fixed his issues with the sidebar and header. I would say to make sure you have followed the readme closely. It looks like you may have added the `theme` property to your cards' YAML which is not necessary.

**Comment by Xiondewah** [comment]
I've had a look - I do use layout-card and custom-button card - could these impact it do you think?  I've noticed I can't get the standard weather card to show with the middle-left LCARS as you have in the examples.

Whilst writing, what layout do you use for the entire screen - is it a single column or multiple?  I think it would be helpful if you could add a bit to show how you've built up on of the screens as it will save an awful lot of fiddling about trying bits out :-)

Definitely want to get this to work as I've been wanting LCARS for a very long time!

J

**Comment by Xiondewah** [comment]
I'm really struggling to make any progress on resolving this.  I only have a few HACS front-end integrations and 1 other theme installed, but I don't know what else to try.  Incidentally I have tried the reload themes service but it doesn't change anything.  If I move to another dashboard the theme kicks in other than the gaps between buttons on the sidebar, but if I refresh the browser, the sidebar goes again and I have to reset to the standard theme.

**Comment by Xiondewah** [comment]
![Image 06-01-2023 at 12 21](https://user-images.githubusercontent.com/50043329/211011861-7c89d95d-8a93-4592-84f7-3d1189f1cd3b.jpeg)

**Comment by Xiondewah** [comment]
I just removed the layout-card integration but that's only made things worse as the custom-gap card seems to have gone with it now.

**Comment by th3jesta** [comment]
I do like what you've got so far! But we've gotta get that sidebar and header working for you! Can you verify that the card-mod.js file is in the location you specified in your configuration.yaml? For example:
```yaml
frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/lovelace-card-mod/card-mod.js
```
...check that card-mod.js is there. In case you don't know, the `local` folder is the `www` folder in the root of your HA installation directory.

**Comment by th3jesta** [comment]
It may be helpful if you can provide the full list of front-end mods you've installed from HACS, and if you have anything from the addon-store that modify anything in the UI.

Also, are you on the latest version? Have you modified LCARS.yaml at all?

**Comment by th3jesta** [comment]
Here's the full YAML for one of my dashboards:
```
views:
  - title: Home
    cards:
      - type: vertical-stack
        cards:
          - type: markdown
            content: '# Entryway'
            card_mod:
              class: header
          - show_current: true
            show_forecast: false
            type: weather-forecast
            entity: weather.home
            name: Outside
            card_mod:
              class: middle
          - type: horizontal-stack
            cards:
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: toggle
                entity: cover.garage_door
                icon: mdi:garage-variant
                show_state: true
                icon_height: 30px
                card_mod:
                  class: button-bullet
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: toggle
                entity: light.stairs
                icon: mdi:stairs
                icon_height: 30px
                card_mod:
                  class: button-lozenge
          - type: custom:mail-and-packages-card
            name: Mail Summary
            updated: sensor.mail_updated
            details: true
            image: false
            packages_delivered: sensor.mail_packages_delivered
            packages_in_transit: sensor.mail_packages_in_transit
            fedex_packages: sensor.mail_fedex_packages
            ups_packages: sensor.mail_ups_packages
            usps_packages: sensor.mail_usps_packages
            amazon_packages: sensor.mail_amazon_packages
            usps_mail: sensor.mail_usps_mail
            gif_sensor: sensor.mail_image_system_path
            camera_entity: camera.mail_usps_camera
            camera: true
            card_mod:
              class: footer
      - type: vertical-stack
        cards:
          - type: markdown
            content: '# Front Door'
            card_mod:
              class: header
          - show_state: true
            show_name: true
            camera_view: auto
            type: picture-entity
            entity: camera.front_doorbell_main
            image: https://demo.home-assistant.io/stub_config/bedroom.png
            aspect_ratio: '16:9'
            card_mod:
              class: middle
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: lock.front_door_doorlock
            show_state: true
            name: Front door lock
            card_mod:
              class: footer
```
