### ISSUE TITLE
support for tile card? 

### ISSUE THREAD

**Issue by JonGilmore** [th3jesta/ha-lcars#30]
Has anybody tested the tile card with this theme? I'm new to this theme, but I can't seem to get it render like I'd expect. Here's my code and a screenshot how it renders. 

```yaml
      - type: tile
        entity: group.main_floor_lights
        name: Main
        icon: mdi:lightbulb
        tap_action:
          action: navigate
          navigation_path: "/ui-lcars/lights-main"
        icon_tap_action:
          action: call-service
          service: button.press
          target:
            entity_id: button.basement_equipment_room_phantom_kp_position_1_keypad_main_off
        card_mod:
          class: button-bullet
```

<img width="611" alt="image" src="https://user-images.githubusercontent.com/7232986/211153912-b25f7d5e-fd43-4d63-a540-fb0bf0b31a2a.png">

**Comment by th3jesta** [comment]
I haven't addressed that card specifically yet. I assume you are wanting it to render like the button-bullet? In your screenshot, it looks like Tile is functionally jus ta button, so I would recommend making a button for you Main light, and then applying the bullet class to it for the following effect (in your selected theme colors, of course):
<img width="265" alt="image" src="https://user-images.githubusercontent.com/38670315/211355787-bb4c5fb4-4574-41c5-8743-5a6add20b117.png">

**Comment by JonGilmore** [comment]
Thanks! I liked the `icon_tap_action` vs `tap_action` that the tile card offers, but it looks like I can make this same functionality work with `tap_action` and `double_tap_action`.
For anybody that stumbles upon this, here's what I ended up doing.

```
          - type: button
            entity: group.main_floor_lights
            icon: mdi:lightbulb
            name: Main
            show_state: true
            tap_action:
              action: call-service
              service: button.press
              data:
                entity_id: button.basement_equipment_room_phantom_kp_position_1_keypad_main_off
            double_tap_action:
              action: navigate
              navigation_path: "/ui-lcars/lights-main"
            card_mod:
              class: button-bullet
```
