### ISSUE TITLE
[Feature Request] Right-justified Text for right-justified header/footer

### ISSUE THREAD

**Issue by mermelmadness** [th3jesta/ha-lcars#47]
![image](https://user-images.githubusercontent.com/38080873/214450381-e54463d5-1cc3-4245-bef4-47157a071045.png)
There should be a `header-right` and `footer-right` that right-justifies the text, too.

**Comment by smugleafdev** [comment]
This is easily accomplished via the card mod:

```yaml
    card_mod:
      class: middle-right
      style: |
        ha-card {
          text-align: right;
        }
```
