### ISSUE TITLE
javascript_version from your frontend config is no longer supported

### ISSUE THREAD

**Issue by askpatrickw** [th3jesta/ha-lcars#67]
I'm seeing this in my logs:

```
Logger: homeassistant.components.frontend
Source: components/frontend/__init__.py:335
Integration: Home Assistant Frontend (documentation, issues)
First occurred: 00:05:46 (1 occurrences)
Last logged: 00:05:46

Please remove javascript_version from your frontend config. It is no longer supported
```

https://github.com/home-assistant/core/pull/23618

Is this config no longer needed at all?

**Comment by askpatrickw** [comment]
I removed this from my `configuration.yaml` and haven't had any issues.

Maybe just remove it from the README?

```yaml
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /config/www/community/lovelace-card-mod/card-mod.js
```
