### ISSUE TITLE
Place text or icon on LCARS borders?

### ISSUE THREAD

**Issue by smugleafdev** [th3jesta/ha-lcars#75]
In [this LCARS screenshot](https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Lcars_wallpaper.svg/1920px-Lcars_wallpaper.svg.png), note how the left side has labels in the border such as "03-975683".

I would like to be able to do something similar, whether it's text or an icon. If that can be done simply with card-mod, I would like to see the code for it, and it would be a nice addition to the documentation. If that's not possible right now, then this can be labeled an enhancement.

**Comment by smugleafdev** [comment]
![Screenshot 2023-08-29 at 12 23 22 PM](https://github.com/th3jesta/ha-lcars/assets/20119855/86ade3c7-deb6-416b-9cc5-ef890749cc2c)

Okay so this was a colossal PITA but I got it working with card-mod CSS shenanigans. I don't recommend it. I had to add this font as a resource (stylesheet): https://cdn.jsdelivr.net/npm/@mdi/font@7.2.96/css/materialdesignicons.min.css

And then this CSS in Lovelace:

```yaml
  - type: markdown
    card_mod:
      class: middle
      style: |
        ::before {
          font-family: 'Material Design Icons';
          content: "\F01AA";
          font-size: 24px;
          position: absolute;
          left: -30px;
          top: 10px;
          color: #00b3ff;
        }
```
It's not _right_ but it sure does work.

Ideally this LCARS theme could maybe make that significantly easier, but for right now this will do.
