### ISSUE TITLE
Tabbed-cards, the card is not supported properly.

### ISSUE THREAD

**Issue by MichelJourdain** [th3jesta/ha-lcars#96]
When I use the tabbed-cards, For the headers-contained and footer-contained, the corners are square instead of having the round corners.  Same thing for headers and footer.

![IMG_8878](https://github.com/th3jesta/ha-lcars/assets/83040228/3bb4ed9d-8015-4cd2-8484-abd2f2d6348a)

 ```   
- type: custom:tabbed-card
    styles:
      --mdc-theme-primary: yellow
      --mdc-tab-text-label-color-default: lightblue
    options: {}

    tabs:
      - card:
          type: vertical-stack
          cards:
            - type: markdown
              content: "# Météo"
              card_mod:
                class: bar

            - type: custom:layout-card
              layout_type: custom:horizontal-layout
              layout:
                width: 360
                max_cols: 3
              cards:
                - type: vertical-stack
                  cards:
                  
                    - type: markdown
                      content: "# Prévisions"
                      card_mod:
                        class: header-contained

                    - !include ../Cartes/Carte-Meteo.yaml

                    - type: markdown
                      card_mod:
                         class: footer-contained
                      content: "## &nbsp;"
```
